### ISSUE TITLE
What about the project ?

### ISSUE THREAD

**Issue by Konsilion** [OpenTerrace/openterrace-python#1]
Hi,

I'm impressed by the work done but I can't get OpenTerrace to run...

In the documentation the installation steps are missing but it would be a pleasure to work with you to make the installation available with Conda-forge

**Comment by jakobhaervig** [comment]
Hi,

Thanks for the comment. Lately, I haven't had much time but I plan to focus here again soon. I would be happy to collaborate on this project and setup installation via pip or conda. 
I'll get back to you after summer holidays.

Thanks for reaching out,
Jakob

**Comment by jakobhaervig** [comment]
> Hi,
> 
> I'm impressed by the work done but I can't get OpenTerrace to run...
> 
> In the documentation the installation steps are missing but it would be a pleasure to work with you to make the installation available with Conda-forge

Hi again,

Can you drop me an email at jah@energy.aau.dk and we can discuss how to proceed?

Best and thanks,
Jakob
