### ISSUE TITLE
Update citation.cff

### ISSUE THREAD

**Issue by AdamRJensen** [OpenTerrace/openterrace-python#104]
The CITATION.cff file should be updated to point to the final JOSS paper once/if this is accepted.

This issue should not be addressed right now but is opened as a reminder once the JOSS review process is complete.

**Comment by jakobhaervig** [comment]
This has been resolved in https://github.com/OpenTerrace/openterrace-python/commit/1c62a346bd8d1628bd9c696f049322a95c7c7f2a
