### ISSUE TITLE
Put JOSS files in a folder

### ISSUE THREAD

**Issue by AdamRJensen** [OpenTerrace/openterrace-python#105]
Right now the files for the JOSS submission is cluttering the repo. I suggest putting the files in a folder called "paper".

I'm not exactly sure how you need to specify this to joss, but you can probably find the info here: https://joss.readthedocs.io/en/latest/index.html

**Comment by jakobhaervig** [comment]
Thanks, I now moved the paper.md and paper.bib to their own folder for a cleaner repo.
