### ISSUE TITLE
Implement versioning of software

### ISSUE THREAD

**Issue by AdamRJensen** [OpenTerrace/openterrace-python#106]
It seems like the package does not have a version at the moment (I noticed 0.0.0 in the pyproject.toml file).

I recommend using Semantic versioning https://semver.org and making a tagging release. I suggest starting at version 0.1.0.

If you need help with this process, let me know.

**Comment by AdamRJensen** [comment]
That's perfectly fine, I was unaware 😄 

I would suggest adding a comment next to the 0.0.0 that versioning is handled dynamically by Poetry

**Comment by jakobhaervig** [comment]
Added comment as you suggest 😄

Closing this one.
