### ISSUE TITLE
Specify doc requirements in file

### ISSUE THREAD

**Issue by AdamRJensen** [OpenTerrace/openterrace-python#107]
Currently, the requirements for building the documentation is hardcoded in the GitHub action [docs.yml](https://github.com/OpenTerrace/openterrace-python/blob/main/.github/workflows/docs.yml).

This is not ideal for other users who want to build the documentation. Also, I highly suggest specifying a version for all the major documentation dependencies to avoid bugs and undesirable changes down the road as new versions of packages are released.

This is probably most easily achieved by having a requirements.txt file in the docs folder.

**Comment by jakobhaervig** [comment]
Thanks for the comment! 
I now changed both the actions for automated tests and doc generation to use the package list in pyproject.toml. This is only place where package information is listed, which helps keeping it all tidy and in sync :-)

Closing this one.

**Comment by AdamRJensen** [comment]
Is it correct that you only use poetry for building the documentation? As per this line:

https://github.com/OpenTerrace/openterrace-python/blob/8b37a9cd912432f305d266e888c789d331ffb37f/pyproject.toml#L50

**Comment by jakobhaervig** [comment]
I use Poetry for building the package, which is being uploaded to PyPI. Poetry also manages internal package dependencies. Line 50 

Line 33-41 specify additional packages required only when building the documentation.

Line 50 specifies the build backend, which is Poetry. Also additional dependencies such as the dynamic versioning plugin is specified.

**Comment by jakobhaervig** [comment]
@AdamRJensen, all dependencies have now been locked 👍🏻
