### ISSUE TITLE
Layer numbering

### ISSUE THREAD

**Issue by AdamRJensen** [OpenTerrace/openterrace-python#141]
First, I think it would be very useful including this figure from the JOSS paper in the documentation:
<img width="391" alt="image" src="https://github.com/OpenTerrace/openterrace-python/assets/39184289/edec2062-e1cf-487c-8bd5-c3ed8abd43bb">

Second, it seems that there is an issue with the numbering. The text states that "For each node, the bed material is discretised in M nodes", however if the nodes start at 0 and ends at M, there will be M+1 nodes. I suggest either starting from 0 or ending at M-1.

**Comment by jakobhaervig** [comment]
Good points @AdamRJensen. I now updated the figure and included the updated figure in the documentation in the theory section: https://openterrace.github.io/openterrace-python/theory/

Closing this one.

**Comment by AdamRJensen** [comment]
@jakobhaervig The image does not render correctly

**Comment by jakobhaervig** [comment]
Thanks, please check again.
