### ISSUE TITLE
Mixed use of camelCase and snake_case

### ISSUE THREAD

**Issue by AdamRJensen** [OpenTerrace/openterrace-python#145]
I noticed that the parameter arguments use a mix of camel case (e.g., `fixedValue`) and snake case (e.g., `central_difference`)

For example this example in the tutorials:

        fluid.select_schemes(diff='central_difference_1d', conv='upwind_1d')
        fluid.select_initial_conditions(T=273.15+20)
        fluid.select_massflow(mdot=0.1)
        fluid.select_bc(bc_type='fixedValue',

**Comment by jakobhaervig** [comment]
Thanks, this should now be consistent throughout using PEP 8.

Closing this one.
