### ISSUE TITLE
Space between tutorial and number

### ISSUE THREAD

**Issue by AdamRJensen** [OpenTerrace/openterrace-python#147]
A minor comment that you can feel free to ignore, but there seems to be missing a space around the tutorials and number, e.g., "Tutorial1" should be "Tutorial 1".

<img width="119" alt="image" src="https://github.com/OpenTerrace/openterrace-python/assets/39184289/cee336ea-ba94-4791-b8d3-9d1b072fe246">

**Comment by jakobhaervig** [comment]
Thanks for attention to detail :-) Fixed now.

Closing this one.
