### ISSUE TITLE
JOSS Review: Documentation

### ISSUE THREAD

**Issue by baperry2** [OpenTerrace/openterrace-python#168]
Statement of need: 

- [x] Adding a bit more detail on the uses of the code on the landing page of the documentation would be helpful

Installation instructions:

- [x] See installation comments in #167

Example usage: 

- [x] Sample results are missing for Tutorial 7
- [x] It would be helpful to have a bit more detail on what each tutorial is, as well as a sentence or two describing the results in addition to the figures.

Automated tests:

- [x] There are automated tests that run through a github workflow when PRs are merged. However, this is largely undocumented. Adding a bit to the documentation about these tests and how users/potential developers can run them would be helpful.

**Comment by jakobhaervig** [comment]
Thanks for these comments.
- I added a bit more information on the documentation landing page while still trying to keep it simple.
- All tutorials have been updated with a description in the header.
- I added some information in the header of each automated test.

**Comment by baperry2** [comment]
Thanks for the link to the commit. 

Sample results are still missing for tutorial 7: https://openterrace.github.io/openterrace-python/tutorials/tutorial_7/

**Comment by jakobhaervig** [comment]
Results for tutorial 7 were added here https://github.com/OpenTerrace/openterrace-python/commit/8e42b2f0308d9464a6cba1e793e2ac98e41a3402. Thanks!

**Comment by baperry2** [comment]
That commit doesn't appear to have been merged into your main branch (the online docs linked above still don't show the figure). But that's minor and will presumably get merged eventually so I'll close this issue.
