### ISSUE TITLE
Modify user guide

### ISSUE THREAD

**Issue by AdamRJensen** [OpenTerrace/openterrace-python#181]
When clicking the user guide in the top nav bar, the user is taken to this site:

![image](https://github.com/OpenTerrace/openterrace-python/assets/39184289/53428592-adac-438e-8022-dc76af32c010)

Here it's very easy to miss the content in the left nav bar which is the real content of the user guide. The user guide landing page only links to other high level sections (installation and tutorials) and does not introduce the actual content. I suggest revising and instead of the current content give an introduction to the actual content/sections of the user guide

**Comment by jakobhaervig** [comment]
Thanks, https://github.com/OpenTerrace/openterrace-python/commit/651730b0eccd900197aaca645415526a4abeb83b now includes a new landing page for the user guide.
