### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by AdamRJensen** [OpenTerrace/openterrace-python#182]
I created a clean conda environment based on Python 3.11:

    conda create -n openterrace python=3.11

and subsequently tried to pip install openterrace:

    pip install openterrace

However, I was met with the following error:
![image](https://github.com/OpenTerrace/openterrace-python/assets/39184289/70bfe296-39d4-49da-b434-4435f25c7582)

**Comment by jakobhaervig** [comment]
Thanks for trying out the installation. Make sure to carefully follow all steps in the [installation](https://openterrace.github.io/openterrace-python/installation/#install-openterrace-using-pip-for-regular-users). It seems like you are missing pip in the conda environment. To create the conda environment you have to do:

`conda create -n ot python=3.11.8 pip`

**Comment by AdamRJensen** [comment]
Pip works fine for all other packages:
![image](https://github.com/OpenTerrace/openterrace-python/assets/39184289/b9c27838-1114-4e33-9177-85f3c8a22c62)

**Comment by AdamRJensen** [comment]
The issue seems to be that the package does not work on the latest 3.11 version (3.11.9). When I create a 3.11.9 environment as such:

    conda create -n openterrace3 python=3.11.9 pip

the same error as previous shows up:

![image](https://github.com/OpenTerrace/openterrace-python/assets/39184289/a2bbc56f-172d-4edf-b207-af3164c85eda)

**Comment by jakobhaervig** [comment]
Thanks for the suggestion :-)

Long story short: Initially I did specify minimum versions but I ran into trouble trouble with dependencies and especially the Numba version supplied with Conda. 
Also, in `.github/workflows/pytest.yml` I extract Python version from the `pyproject.toml` on line 36. Specifying a minimum Python version number complicates this line if the version isn't hardcoded `pyproject.toml`. Any ideas welcome here!

For the above reasons I decided to simply fix all versions and suggest installing OpenTerrace into a virtual environment (which I think is best practice anyway).

If you see any specific reason to loosen up the versioning let me know and I'll spend some time on this. Otherwise, I suggest sticking with fixed versions.

**Comment by AdamRJensen** [comment]
Conda can be a bit tricky, which is why I tend to prefer pip tbh.

I'm convinced that it is rather poor practice to be this restrictive in the dependencies when there's no extraordinary reason. In fact, I've never encountered a package that required a specific minor version of python

for the tests, I also will suggest using

**Comment by jakobhaervig** [comment]
Thanks, I found a way to loosen up version req. Now only minimum versions are specified throughout.

Regarding the test matrix, I prefer to keep it nice and tidy by letting it read Python version from pyproject.toml by `python-version-file: ['pyproject.toml']`

**Comment by jakobhaervig** [comment]
I agree! But specifying e.g. "3.12" will only test the newest current version/minor version, e.g. 3.12.3.. What if people are using 3.12.2? Wouldn't the test matrix have to include all micro versions as well? It shouldn't break it but we never know :)

**Comment by AdamRJensen** [comment]
> I agree! But specifying e.g. "3.12" will only test the newest current version/minor version, e.g. 3.12.3.. What if people are using 3.12.2? Wouldn't the test matrix have to include all micro versions as well? It shouldn't break it but we never know :)

The third digit denotes the "patch version", and according to the [semantic version ](https://semver.org/) guidelines should only include "backward compatible bug fixes". Therefore, it's a fairly safe assumption to only test minor versions (e.g., 3.10, 3.11)

**Comment by jakobhaervig** [comment]
@AdamRJensen, https://github.com/OpenTerrace/openterrace-python/commit/6de0fc88397b45d4f8ea7b3eda449f1798e17c3c now tests ["3.9", "3.10", "3.11", "3.12"]. I would expect noone else than the reviewer to continuously update this in future when 3.13 is released ;-)
