### ISSUE TITLE
Output parameters

### ISSUE THREAD

**Issue by AdamRJensen** [OpenTerrace/openterrace-python#183]
In the source code part (documentation) I did not see a description of any outputs -- perhaps I missed this?

I realize that most functions are modifications to a class as part of setting up the problem, and thus only have inputs.

I imagine that it's the `RUN_SIMULATION()` part that has outputs?

**Comment by jakobhaervig** [comment]
Good point! I updated the run_simulation function with bit more explanation https://github.com/OpenTerrace/openterrace-python/pull/188/commits/5a26dc9440d71541601d91905c11585599705f4b.
