### ISSUE TITLE
Statement of need in doumentation

### ISSUE THREAD

**Issue by AdamRJensen** [OpenTerrace/openterrace-python#191]
The JOSS review asks for:
> A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?

This is well done in the paper, but I do not see it in the documentation.

Please correct me if I have missed it. Otherwise, I suggest adding a sentence or two to the landing page stating the need (copy from the paper)

**Comment by jakobhaervig** [comment]
Thanks for the suggestion. Now added in https://github.com/OpenTerrace/openterrace-python/commit/6b871b6287101fcd54687326de04cfdb460df890
