### ISSUE TITLE
List not rendering correctly in JOSS paper

### ISSUE THREAD

**Issue by AdamRJensen** [OpenTerrace/openterrace-python#192]
The list in the summary is currently not rendering correctly:
![image](https://github.com/OpenTerrace/openterrace-python/assets/39184289/5dd67d68-57d2-4daa-acc4-bdaf1f7b3acd)

I suggest trying to add a blank line before the list, otherwise we might have to try and reach out to the JOSS editorial staff and ask for some help.

**Comment by jakobhaervig** [comment]
Thanks! This is now corrected
