### ISSUE TITLE
Add documentation URL to GitHub landing page

### ISSUE THREAD

**Issue by AdamRJensen** [OpenTerrace/openterrace-python#95]
On a repository's GitHub page, it's possible to add a URL in the top right - this makes it easy to navigate to the documentation page. I suggest adding this to this repo. See the screenshot from the pandas GH page as an example:

<img width="853" alt="image" src="https://github.com/OpenTerrace/openterrace-python/assets/39184289/e09dfb4d-e08b-4541-bcce-9b866f69ac4d">

**Comment by jakobhaervig** [comment]
Hi @AdamRJensen,

Thanks for the heads up. A link can now be found in the right hand side!

Thanks,
Jakob
